id: https://concepts.datalad.org/s/roles/unreleased
name: roles-schema
version: UNRELEASED
status: eunal:concept-status/DRAFT
title: Schema for characterizing relationships with roles
description: |
  This schema provides the most basic classes and slots to qualify
  relationships between two things. The connection to the
  [thing-schema](../../thing) is the [`qualified_relations`](qualified_relations)
  slot, which can be used to qualify relations between things via any number
  of [`Relationship`](Relationship) declarations.

  Each `Relationship` links one object (`Thing`) to a subject (`Thing`) and
  associates one or more roles ([`Role`](Role)) with this relationship via the
  [`roles`](roles) slot.

  A `Role` is itself a `Thing`, and can be annotated with (inline)
  attributes as needed. However, typically it should be sufficient
  to reference a role by a URI.

  This schema also incorporates the schemas

  - [`things`](https://concepts.datalad.org/s/things/v1)

  The schema definition is available as

  - [JSON-LD context](../unreleased.context.jsonld)
  - [LinkML YAML](../unreleased.yaml)
  - [OWL TTL](../unreleased.owl.ttl)
  - [SHACL TTL](../unreleased.shacl.ttl)

comments:
  - ALL CONTENT HERE IS UNRELEASED AND MAY CHANGE ANY TIME

license: MIT

prefixes:
  dcat: http://www.w3.org/ns/dcat#
  dlroles: https://concepts.datalad.org/s/roles/unreleased/
  dlschemas: https://concepts.datalad.org/s/
  dlthings: https://concepts.datalad.org/s/things/v1/
  dltypes: https://concepts.datalad.org/s/types/unreleased/
  eunal: http://publications.europa.eu/resource/authority/
  ex: http://example.org/
  linkml: https://w3id.org/linkml/
  marcrel: http://id.loc.gov/vocabulary/relators/
  prov: http://www.w3.org/ns/prov#
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  skos: http://www.w3.org/2004/02/skos/core#

default_prefix: dlroles

emit_prefixes:
  - dlroles
  - dlthings
  - dltypes
  - marcrel
  - rdf
  - rdfs
  - skos

imports:
  - dlschemas:things/v1


slots:
  roles:
    slot_uri: dlroles:roles
    description: >-
      Describes the function of an entity or agent (object) within the scope of
      a `Relationship` with the subject.
    range: Role
    multivalued: true
    inlined: false
    exact_mappings:
      - prov:hadRole
      - dcat:had_role

  qualified_relations:
    slot_uri: dlroles:qualified_relations
    description: >-
      Characterizes the relationship or role of an entity with respect to the subject.
    domain: Thing
    range: Relationship
    inlined: true
    inlined_as_list: true
    multivalued: true
    exact_mappings:
      - dcat:qualifiedRelation


classes:
  Role:
    class_uri: dlroles:Role
    is_a: Thing
    description: >-
      A role is the function of a resource or agent with respect to a subject,
      in the context of resource attribution or relationships.
    exact_mappings:
      - prov:Role
      - dcat:Role

  Relationship:
    class_uri: dlroles:Relationship
    description: >-
      An association class for characterizing the relation between two things with
      the role(s) the object had with respect to the subject. A relationship is
      always between two things only, but can be annotated with multiple roles
      (for example, a person having both an author role with respect to a dataset,
      and also being the person who is legally responsible contact for it).
    slots:
      - object
      - roles
      - schema_type
    slot_usage:
      object:
        required: true
        range: Thing
    close_mappings:
      - prov:Influence
      - dcat:Relationship
