name: Build and deploy website

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install hatch
        # click version is temporary fix for https://github.com/pypa/hatch/issues/2050
        run: uv tool install hatch --with 'click <8.3'

      - name: Set up Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Build
        # this is building a branch specific site
        # when multiple branches/versions are maintained concurrently
        # we likely need to build all of them and do a joint upload
        run: |
          hatch run docs:build
          mv ./build/mkdocs-site ./build/upload

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the directory created by mkdocs
          path: ./build/upload

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub pages
        id: deployment
        uses: actions/deploy-pages@v4
